backend:
  name: git-gateway

local_backend:
  allowed_hosts: ['beeper.local']

media_folder: "src/static/media"
public_folder: "/static/media"

collections:
  - label: "Home"
    name: "home"
    editor:
      preview: false
    files:
      - label: "Site Settings"
        name: "site"
        file: "src/_data/site.yaml"
        fields:
          - { label: Logo, name: logo, widget: image }
          - { label: Name, name: name, widget: string }
          - { label: Phone, name: phone, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: "About", name: "about", widget: "markdown" }
          - { label: URL, name: url, widget: string }
      - label: "Navigation"
        name: "navigation"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Services"
        name: "services"
        file: "src/_data/services.yaml"
        fields:
          - label: Service
            name: services
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Picture, name: picture, widget: image }
              - { label: Description, name: desc, widget: markdown }

      - label: "Portfolio"
        name: "portfolio"
        file: "src/_data/portfolio.yaml"
        fields:
          - label: Portfolio
            name: portfolio
            widget: list
            collapsed: false
            fields:
              - { label: Name, name: name, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Desktop Image, name: desktop, widget: image }
              - { label: Mobile Image, name: mobile, widget: image }
              - { label: Description, name: desc, widget: markdown }